language: node_js
node_js:
- '0.10'
env:
  matrix:
  - JOB=unit
  - JOB=e2e BROWSER=chrome
  - JOB=e2e BROWSER=firefox
  - JOB=e2e BROWSER='internet explorer' OS='Windows 7' BROWSER_VERSION=10
  global:
  - LOGS_DIR: /tmp/sauce-build/logs
  - BROWSER_PROVIDER_READY_FILE: /tmp/sauce-connect-ready
  - SAUCE_USERNAME: macgyver-ci
  - SAUCE_ACCESS_KEY: 5aa3c19a-1374-439d-8777-cfd7521eb740
before_script:
- mkdir -p $LOGS_DIR
- ./misc/sauce/sauce_connect_setup.sh
- npm install -g bower grunt-cli
- bower install --config.interactive=false
- ./misc/travis/wait_for_ready_file.sh
script:
- ./misc/travis/run.sh
